<?xml version="1.0" encoding="UTF-8"?>
<!--       
        Bayesian network in XMLBIF v0.3 (BayesNet Interchange Format)
        Produced by SBN4R (Simple Bayesian Network library for Ruby)
        Output created Sat Jan 27 17:00:04 -0700 2007
 -->

<!-- DTD for the XMLBIF 0.3 format -->
<!DOCTYPE bif [
  <!ELEMENT bif (network)*>
  <!ATTLIST bif version CDATA #REQUIRED>
  <!ELEMENT network (name, (property | variable | definition)*)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT variable (name, (outcome | property)*)>
  <!ATTLIST variable type (nature | decision | utility) "nature">
  <!ELEMENT outcome (#PCDATA)>
  <!ELEMENT definition (for | given | table | property)*>
  <!ELEMENT for (#PCDATA)>
  <!ELEMENT given (#PCDATA)>
  <!ELEMENT table (#PCDATA)>
  <!ELEMENT property (#PCDATA)>
]>
<bif version="0.3">
  <network>
    <name>Grass_Wetness_Belief_Net</name>

    <!-- Variables -->
    <variable type="nature">
      <name>Cloudy</name>
      <outcome>true</outcome>
      <outcome>false</outcome>
    </variable>
    <variable type="nature">
      <name>Grass_Wet</name>
      <outcome>true</outcome>
      <outcome>false</outcome>
    </variable>
    <variable type="nature">
      <name>Sprinkler</name>
      <outcome>true</outcome>
      <outcome>false</outcome>
    </variable>
    <variable type="nature">
      <name>Rain</name>
      <outcome>true</outcome>
      <outcome>false</outcome>
    </variable>

    <!-- Probability distributions -->
    <definition>
      <for>Cloudy</for>
      <table>0.5 0.5</table>
    </definition>
    <definition>
      <for>Grass_Wet</for>
      <given>Sprinkler</given>
      <given>Rain</given>
      <table>0.99 0.01 0.9 0.1 0.9 0.1 0.0 1.0</table>
    </definition>
    <definition>
      <for>Sprinkler</for>
      <given>Cloudy</given>
      <table>0.1 0.9 0.5 0.5</table>
    </definition>
    <definition>
      <for>Rain</for>
      <given>Cloudy</given>
      <table>0.8 0.2 0.2 0.8</table>
    </definition>
  </network>
</bif>
